In [142]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [143]:
df = pd.read_csv('.\googleplaystore.csv')

In [144]:
# chack the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

In [145]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [146]:
# To get a sample of rendom data
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3704,Video Status,VIDEO_PLAYERS,4.3,6685,4.0M,"1,000,000+",Free,0,Everyone,Video Players & Editors,"August 2, 2018",1.1.4,4.1 and up
4914,AC remote control mobile,TOOLS,3.9,3043,7.7M,"100,000+",Free,0,Everyone,Tools,"June 2, 2017",1.3 acremotecontrol,4.0.3 and up
6755,Corporate B.S. Generator,BUSINESS,NaN,0,6.9M,10+,Free,0,Everyone,Business,"November 20, 2017",1.00,3.0 and up
8286,DC Metro Transit,TRAVEL_AND_LOCAL,4.5,339,10M,"5,000+",Paid,$2.99,Everyone,Travel & Local,"May 13, 2018",5.11.3,4.1 and up
716,Cars Coloring Pages,EDUCATION,4.4,1090,49M,"1,000,000+",Free,0,Everyone,Education;Creativity,"February 3, 2018",1.2.0,4.0 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
476,"Moco+ - Chat, Meet People",DATING,4.2,1545,Varies with device,"10,000+",Paid,$3.99,Mature 17+,Dating,"June 19, 2018",2.6.139,4.1 and up
1451,"591 housing transactions - renting houses, mid...",HOUSE_AND_HOME,4.1,24977,21M,"1,000,000+",Free,0,Everyone,House & Home,"August 1, 2018",3.5.9,4.0.3 and up
6911,Beautiful Widgets Pro,PERSONALIZATION,4.2,97890,14M,"1,000,000+",Paid,$2.49,Everyone,Personalization,"August 24, 2016",5.7.8,2.3 and up
4377,Rope'n'Fly 4,GAME,4.1,234606,59M,"10,000,000+",Free,0,Everyone,Action,"January 29, 2018",3.1,2.3 and up

In [147]:
df.describe()

            Rating       Reviews
count  9367.000000  1.084100e+04
mean      4.191513  4.441119e+05
std       0.515735  2.927629e+06
min       1.000000  0.000000e+00
25%       4.000000  3.800000e+01
50%       4.300000  2.094000e+03
75%       4.500000  5.476800e+04
max       5.000000  7.815831e+07

# Assighnment: write down all the numaric variables and make them numaric
1.size\
2.install\
3.price

In [148]:
df['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

In [149]:
# to do that let's check the  unique values
df['Size'].value_counts()

Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
430k                     1
429k                     1
200k                     1
460k                     1
619k                     1
Name: count, Length: 461, dtype: int64

# check that how maney MBs are there in one Kb? and how to calculate?
1. convert KB to MB
2. Then remove the M from all numbers\
3.  Handel`Varies with device`

In [150]:
# Function to convert KB to MB
def convert_kb_to_mb(size):
    return size / 1024

# Function to remove 'M' from numbers
def remove_m_from_number(size):
    return size.rstrip('M')

# Convert 'Size' from KB to MB and remove 'M' from numbers
df['Size'] = df['Size'].apply(lambda x: convert_kb_to_mb(float(x.rstrip('M'))) if isinstance(x, str) and 'M' in x else x)

# Remove 'Varies with device' values
df['Size'] = df['Size'].apply(lambda x: remove_m_from_number(x) if isinstance(x, str) else x)

In [151]:
df['Size'].unique()

array([0.0185546875, 0.013671875, 0.00849609375, 0.0244140625,
       0.002734375, 0.00546875, 0.0283203125, 0.0322265625, 0.00302734375,
       0.02734375, 0.01171875, 0.01953125, 0.0205078125, 0.0361328125,
       0.00263671875, 0.00537109375, 0.0166015625, 0.0380859375,
       0.0302734375, 0.0041015625, 0.0068359375, 0.0224609375,
       0.005859375, 0.00595703125, 0.0044921875, 0.008984375, 0.005078125,
       0.0107421875, 0.0234375, 'Varies with device', 0.0091796875,
       0.0146484375, 0.009765625, 0.001171875, 0.025390625, 0.0078125,
       0.00771484375, 0.0546875, 0.0556640625, 0.0341796875, 0.052734375,
       '201k', 0.003515625, 0.00556640625, 0.0083984375, 0.00234375,
       0.0263671875, 0.00244140625, 0.015625, 0.0033203125, 0.00869140625,
       0.00380859375, 0.00283203125, 0.037109375, 0.03125, 0.0052734375,
       0.017578125, 0.00107421875, 0.0021484375, 0.00439453125,
       0.0095703125, 0.05078125, 0.0087890625, 0.00654296875, 0.029296875,
       0.0025390625, 0.00693359375, 0.00361328125, 0.021484375,
       0.0072265625, 0.00625, 0.003125, 0.0080078125, 0.00966796875,
       0.00478515625, 0.00927734375, 0.0048828125, 0.00576171875,
       0.0126953125, 0.0712890625, 0.006640625, 0.00341796875, 0.00390625,
       0.00224609375, 0.00703125, 0.00205078125, 0.041015625,
       0.00712890625, 0.00888671875, 0.0537109375, '23k', 0.00634765625,
       0.00146484375, 0.00732421875, 0.0498046875, 0.0400390625, 0.046875,
       0.00830078125, 0.044921875, 0.00810546875, 0.00419921875,
       0.00458984375, 0.00322265625, 0.0390625, 0.0076171875, 0.00859375,
       0.0064453125, 0.00498046875, 0.0595703125, 0.064453125, '79k',
       0.008203125, '118k', 0.04296875, '695k', 0.0015625, 0.0060546875,
       '18k', 0.0517578125, 0.0013671875, 0.0029296875, 0.0056640625,
       0.0037109375, 0.009375, 0.0439453125, 0.0615234375, 0.0478515625,
       0.0751953125, 0.004296875, 0.0046875, 0.068359375, 0.00673828125,
       0.00908203125, 0.00791015625, 0.03515625, 0.08203125, 0.0947265625,
       0.001953125, 0.00185546875, 0.0017578125, 0.00517578125,
       0.0458984375, '556k', '526k', 0.07421875, 0.007421875,
       0.0576171875, 0.00947265625, 0.076171875, 0.0703125, 0.0419921875,
       0.00751953125, 0.00615234375, '334k', 0.033203125, 0.0908203125,
       0.0634765625, 0.0771484375, 0.09765625, 0.056640625, 0.048828125,
       0.06640625, 0.0625, 0.0654296875, 0.05859375, 0.091796875, '232k',
       0.0966796875, '624k', 0.0927734375, '8.5k', '41k', '292k', '11k',
       0.078125, 0.00166015625, 0.072265625, 0.060546875, 0.0673828125,
       0.0732421875, 0.095703125, 0.0830078125, 0.080078125, 0.09375,
       0.0849609375, 0.0693359375, 0.083984375, 0.0888671875,
       0.0791015625, 0.08984375, 0.0810546875, 0.0859375, '704k', '862k',
       '899k', '378k', '266k', '375k', 0.00126953125, '975k', '980k',
       0.00400390625, 0.0869140625, '696k', '544k', '525k', '920k',
       '779k', '853k', '720k', '713k', '772k', '318k', '58k', '241k',
       '196k', '857k', '51k', '953k', '865k', '251k', '930k', '540k',
       '313k', '746k', '203k', '26k', '314k', '239k', '371k', '220k',
       '730k', '756k', '91k', '293k', '17k', '74k', '14k', '317k', '78k',
       '924k', '902k', '818k', '81k', '939k', '169k', '45k', '475k',
       '965k', 0.087890625, '545k', '61k', '283k', '655k', '714k', '93k',
       '872k', '121k', '322k', 0.0009765625, '976k', '172k', '238k',
       '549k', '206k', '954k', '444k', '717k', '210k', '609k', '308k',
       '705k', '306k', '904k', '473k', '175k', '350k', '383k', '454k',
       '421k', '70k', '812k', '442k', '842k', '417k', '412k', '459k',
       '478k', '335k', '782k', '721k', '430k', '429k', '192k', '200k',
       '460k', '728k', '496k', '816k', '414k', '506k', '887k', '613k',
       '243k', '569k', '778k', '683k', '592k', '319k', '186k', '840k',
       '647k', '191k', '373k', '437k', '598k', '716k', '585k', '982k',
       '222k', '219k', '55k', '948k', '323k', '691k', '511k', '951k',
       '963k', '25k', '554k', '351k', '27k', '82k', '208k', '913k',
       '514k', '551k', '29k', '103k', '898k', '743k', '116k', '153k',
       '209k', '353k', '499k', '173k', '597k', '809k', '122k', '411k',
       '400k', '801k', '787k', '237k', '50k', '643k', '986k', '97k',
       '516k', '837k', '780k', '961k', '269k', '20k', '498k', '600k',
       '749k', '642k', '881k', '72k', '656k', '601k', '221k', '228k',
       '108k', '940k', '176k', '33k', '663k', '34k', '942k', '259k',
       '164k', '458k', '245k', '629k', '28k', '288k', '775k', '785k',
       '636k', '916k', '994k', '309k', '485k', '914k', '903k', '608k',
       '500k', '54k', '562k', '847k', '957k', '688k', '811k', '270k',
       '48k', '329k', '523k', '921k', '874k', '981k', '784k', '280k',
       '24k', '518k', '754k', '892k', '154k', '860k', '364k', '387k',
       '626k', '161k', '879k', '39k', '970k', '170k', '141k', '160k',
       '144k', '143k', '190k', '376k', '193k', '246k', '73k', '658k',
       '992k', '253k', '420k', '404k', '470k', '226k', '240k', '89k',
       '234k', '257k', '861k', '467k', '157k', '44k', '676k', '67k',
       '552k', '885k', '1020k', '582k', '619k'], dtype=object)

In [152]:
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2688,"Real Estate, Car, Shopping and Others",SHOPPING,4.3,568273,Varies with device,"10,000,000+",Free,0,Everyone,Shopping,"August 4, 2018",Varies with device,Varies with device
174,English translation from Bengali,BOOKS_AND_REFERENCE,4.5,527,0.002832,"100,000+",Free,0,Everyone,Books & Reference,"March 31, 2018",14.0,4.0 and up
7313,BF CG View Wallpapers,FAMILY,3.6,13,0.002441,"1,000+",Free,0,Teen,Entertainment,"June 19, 2015",3.0,3.0 and up
10271,FC Red Bull Salzburg App,SPORTS,4.5,1526,0.086914,"50,000+",Free,0,Everyone,Sports,"August 7, 2018",4.0.4-R,5.0 and up
9797,ES Holo Theme,TOOLS,4.3,11449,0.00166,"500,000+",Free,0,Everyone,Tools,"February 2, 2016",2.0.4,2.0 and up
590,"Hide App, Private Dating, Safe Chat - PrivacyH...",DATING,4.4,35205,0.007031,"1,000,000+",Free,0,Everyone,Dating,"May 21, 2018",2.9.6,4.0 and up
1225,Easy Healthy Recipes,FOOD_AND_DRINK,4.1,278,0.007031,"50,000+",Free,0,Everyone,Food & Drink,"July 20, 2018",24.5.0,4.0 and up
8818,EmuBox - Fast Retro Emulator,GAME,3.9,1576,0.041992,"50,000+",Free,0,Everyone,Arcade,"August 5, 2018",2.1.1,4.1 and up
222,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
2112,PAC-MAN Pop,FAMILY,4.3,24877,0.052734,"5,000,000+",Free,0,Everyone,Puzzle;Action & Adventure,"June 20, 2018",2.1.6579,4.1 and up

In [153]:
df['Installs'].value_counts()

Installs
1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             908
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
0                    1
Name: count, dtype: int64

# do it as numaric column or group that into different group following bining method

In [154]:
# Remove the '+' and ',' from 'Installs' column
df['Installs'] = df['Installs'].str.replace(',', '')
df['Installs'] = df['Installs'].str.replace('+', '')

# Convert 'Installs' column to numeric
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

# Define the bin edges for grouping
bin_edges = [0, 1000, 100000, 10000000, np.inf]
bin_labels = ['0-1K', '1K-100K', '100K-10M', '10M+']

# Group 'Installs' into different bins
df['Installs Group'] = pd.cut(df['Installs'], bins=bin_edges, labels=bin_labels, right=False)

In [155]:
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs Group
7910,CU SoCal Mobile Banking,FINANCE,4.0,253,0.024414,10000,Free,0,Everyone,Finance,"May 2, 2018",4.6.68,4.0.3 and up,1K-100K
6904,Learn SAP BW,BOOKS_AND_REFERENCE,NaN,2,0.019531,500,Free,0,Everyone,Books & Reference,"February 13, 2018",1.1,4.0 and up,0-1K
6416,Lust in Terror Manor - The Truth Unveiled | Otome,GAME,4.1,355,0.051758,10000,Free,0,Teen,Adventure,"July 10, 2018",1.0.6,4.1 and up,1K-100K
699,Duolingo: Learn Languages Free,EDUCATION,4.7,6289924,Varies with device,100000000,Free,0,Everyone,Education;Education,"August 1, 2018",Varies with device,Varies with device,10M+
4305,Magic Tiles - TWICE Edition (K-Pop),GAME,4.4,2351,0.060547,100000,Free,0,Everyone,Music,"July 25, 2018",1009001,4.0 and up,100K-10M
2351,Brilliant Distinctions®,MEDICAL,2.8,78,0.070312,50000,Free,0,Everyone,Medical,"June 27, 2018",2.2.12,4.4 and up,1K-100K
7921,FORUM Credit Union CU Online,FINANCE,4.1,196,0.007129,10000,Free,0,Everyone,Finance,"June 30, 2018",5.0.0,4.4 and up,1K-100K
7857,CT Scan Viewer 3D,MEDICAL,4.2,6,0.02832,1000,Free,0,Everyone,Medical,"June 20, 2018",1.0,2.3 and up,1K-100K
4744,TripAdvisor Hotels Flights Restaurants Attract...,TRAVEL_AND_LOCAL,4.4,1162331,Varies with device,100000000,Free,0,Everyone,Travel & Local,"August 4, 2018",Varies with device,Varies with device,10M+
1974,Bubble Shooter Genies,GAME,4.5,26985,0.040039,5000000,Free,0,Everyone,Casual,"June 4, 2018",1.9.1,4.0.3 and up,100K-10M

# How to handle price?

In [156]:
df['Price'].value_counts()

Price
0         10041
$0.99       148
$2.99       129
$1.99        73
$4.99        72
          ...
$19.90        1
$1.75         1
$14.00        1
$4.85         1
$1.04         1
Name: count, Length: 92, dtype: int64

In [157]:
# Remove the dollar sign from 'Price' column
df['Price'] = df['Price'].str.replace('$', '')
df['Price'] = df['Price'].astype(float) # Convert 'Price' to integer

In [158]:
df.describe()

            Rating       Reviews      Installs         Price
count  9367.000000  1.084100e+04  1.084100e+04  10841.000000
mean      4.191513  4.441119e+05  1.546291e+07      1.027273
std       0.515735  2.927629e+06  8.502557e+07     15.948971
min       1.000000  0.000000e+00  0.000000e+00      0.000000
25%       4.000000  3.800000e+01  1.000000e+03      0.000000
50%       4.300000  2.094000e+03  1.000000e+05      0.000000
75%       4.500000  5.476800e+04  5.000000e+06      0.000000
max       5.000000  7.815831e+07  1.000000e+09    400.000000

In [159]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs Group
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,0.018555,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,1K-100K
1,Coloring book moana,ART_AND_DESIGN,3.9,967,0.013672,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,100K-10M
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,0.008496,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,100K-10M
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,0.024414,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,10M+
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,0.002734,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,100K-10M

In [160]:
df['Type'].value_counts()

Type
Free    10040
Paid      800
Name: count, dtype: int64

# Day-2